# Generated by Django 5.2.5 on 2026-01-22 02:30

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-update_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="lnglat",
            field=models.CharField(
                blank=True,
                help_text="경도,위도 포맷 ex.37,125.5",
                max_length=100,
                null=True,
                validators=[blog.models.lnglat_validator],
                verbose_name="경,위도",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="region",
            field=models.CharField(
                choices=[
                    ("Europe", "유럽"),
                    ("Asia", "아시아"),
                    ("Oceania", "오세아니아"),
                    ("Ameria", "아메리카"),
                    ("Africa", "아프리카"),
                ],
                default="Asia",
                max_length=100,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("title", "content")},
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="댓글쓴이"
                    ),
                ),
                ("message", models.TextField(verbose_name="댓글")),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
            ],
            options={
                "ordering": ["-update_at"],
                "unique_together": {("post", "author", "message")},
            },
        ),
    ]
