# Generated by Django 5.2.5 on 2026-01-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_article_options_remove_article_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="사진"),
        ),
    ]
